apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRESQL_USER: {{ .Values.auth.username }}
  POSTGRESQL_PASSWORD: {{ .Values.auth.password }}
  POSTGRESQL_DATABASE: {{ .Values.auth.database }}
  ADT_DATABASE_URL: "postgresql+asyncpg://{{ .Values.auth.username }}:{{ .Values.auth.password }}@{{ include "postgresql.fullname" . }}:5432/{{ .Values.auth.database }}"
