apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
