apiVersion: v1
kind: Secret
metadata:
  name: adt-ict-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "adt-ict.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADT_DATABASE_URL: "postgresql+asyncpg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@adt-ict-postgresql:5432/{{ .Values.postgresql.auth.database }}"
  ADT_REDIS_URL: "redis://:{{ .Values.redis.auth.password }}@adt-ict-redis:6379/0"
  ADT_CELERY_BROKER_URL: "redis://:{{ .Values.redis.auth.password }}@adt-ict-redis:6379/1"
  ADT_GHES_TOKEN: {{ .Values.secrets.ghesToken | quote }}
