apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ui.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  path: {{ .Values.route.path }}
  to:
    kind: Service
    name: {{ include "ui.fullname" . }}
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
